version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: local-dev
    image: canvas-server-local:latest
    ports:
      - '3000:8080'
    volumes:
      - .:/app
      - .mod:/go/pkg/mod
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - "go run /app/entrypoint/main.go"
    environment:
      - IS_LOCAL=true
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-cred.json